maximilien/softlayer-go

- client/fakes/softlayer_client_fake.go
- client/softlayer_client.go
- services/softlayer_virtual_guest.go
- softlayer/client.go
- utils/ssh_client.go
Hi, @xingzhou and @zhang-hua,
After discussing a bit with @cppforlife on this ssh business, I think my intuition about this behavior not belonging here or in the CPI is correct.
This is behavior that the `bosh-agent` should be doing or if it is not, let's fix the agent so it does.
We can discuss tonight during our call.
Best,
max
Reverts maximilien/softlayer-go#25
> Revert "Refactor the ssh client code"

- .travis.yml
Seems to get past go get vet build step.
> new get link for vet

- data_types/softlayer_virtual_guest.go
- services/softlayer_virtual_guest.go
- services/softlayer_virtual_guest_test.go
- test_fixtures/services/SoftLayer_Virtual_Guest_Service_getObject.json
> Support user data in getObject

- .travis.yml
see if travis passes without gomega
> travis sudo and gomega changes

- client/softlayer_client.go
Found this critical problem when trying to test OS Reload code, it's pretty urgent, since it broke create_vm function, I will try to write the integration test for it later soon, but please review and merge it ASAP. Already passed manual testing in real Softlayer environment. Thanks.
> Fixed a bug where to query stemcell with filter

- client/fakes/softlayer_client_fake.go
1. added check for fslc.DoRawHttpRequestResponses to not be set when using fslc.DoRawHttpRequestResponse
2. added public fields for path and requestType for DoHttpRequestXyz()
> fixed bug in DoHttpRequestXyz()

- services/softLayer_virtual_guest_block_device_template_group.go
- services/softLayer_virtual_guest_block_device_template_group_test.go
- softlayer/softlayer_virtual_guest_block_device_template_group.go
- test_helpers/test_helpers.go
Added a GetTransaction function to the Softlayer_Virtual_Guest_Block_Device_Template_Group_Service, and corresponding unit test
[#102770248]
> Added a WaitforNoActiveTransaction for test_helpers.go

- test_helpers/test_helpers.go
> Changed the condition for an active VGBTG object transaction

- test_helpers/test_helpers.go
> Added check to see if ssh key was already gone before trying to delete it

- data_types/softLayer_network_storage_credential.go
- test_fixtures/services/SoftLayer_Network_Storage_Allowed_Host_Service_getCredential.json
Type of AccountId in getCredential.json  is String
> Fixed  get credential bug

- test_helpers/test_helpers.go
This is used in create_disk integration test clean up
> add DeleteDisk func to test_helpers

- client/softlayer_client.go
> hide credentials in log

- .travis.yml
Changed the crypto/ssh include to golang.org/x/crypto/ssh per discussion in https://github.com/maximilien/softlayer-go/pull/86
> Updated .travis.yaml - SSH

- .travis.yml
- client/softlayer_client_test.go
> Update test for go 1.6

- services/softlayer_network_storage.go
In order to fix issue [132](https://github.com/cloudfoundry/bosh-softlayer-cpi/issues/132) in bosh-softlayer-cpi
> Increased polling time when creating iscsi disk on SL

- services/softlayer_virtual_guest.go
Fixed os_reload when indicating by private ip
> Fixed os_reload when indicating by private ip

- integration/network_storage_lifecycle/network_storage_lifecycle_test.go
- integration/virtual_guest_lifecycle/virtual_guest_lifecycle_test.go
- services/softlayer_network_storage.go
- services/softlayer_network_storage_test.go
- test_fixtures/services/SoftLayer_Account_Service_getIscsiNetworkStorage.json
- test_helpers/test_helpers.go
@maximilien This PR is for addressing [tracker task 127370877](https://www.pivotaltracker.com/story/show/127370877), I added unit tests for the positive and negative paths and integration test. Please review. Thanks.
> Allow to customize interval and timeout for iSCSI disk creation

- services/softlayer_virtual_guest.go
- services/softlayer_virtual_guest_test.go
- test_fixtures/services/SoftLayer_Virtual_Guest_Service_getUpgradeItemPrices_mismatch.json
- test_fixtures/services/SoftLayer_Virtual_Guest_Service_getUpgradeItemPrices_san.json
@maximilien This PR is for addressing [tracker 126844449](https://www.pivotaltracker.com/story/show/126844449), added unit test cases for positive and negative paths. Please help review. Thanks.
> Need to keep the type of system disk and ephemeral disk consistent

- integration/dns_domain/dns_domain_test.go
- services/softlayer_dns_domain.go
- services/softlayer_dns_domain_test.go
- softlayer/softlayer_dns_domain_service.go
- test_fixtures/services/SoftLayer_Dns_Domain_getByDomainName.json
implementation of [SoftLayer_Dns_Domain::getByDomainName](http://sldn.softlayer.com/reference/services/SoftLayer_Dns_Domain/getByDomainName)
> implementation of SoftLayer_Dns_Domain::getByDomainName

- client/http_client.go
DCO 1.1 Signed-off-by: Yuriy Bondaruk <bondyk@gmail.com>
In case of error occurred (like validation error) SoftLayer return response with code 500 and actual error message in the body. 
For example, it could happen that hostname contains underscore char but it's forbidden according to SL rules. In such case softlayer-go was returning generic error message 'HTTP error code: "500"' without actual message.
This fix is checking for SL error message in http body in case of unsuccessful response and returns it.
It works for all requests to SoftLayer.
The issue was discovered in terraform (https://github.com/hashicorp/terraform):
https://github.com/hashicorp/terraform/issues/9241
> Return actual error message from SoftLayer instead of generic error

- client/fakes/softlayer_client_fake.go
- client/softlayer_client.go
- data_types/softlayer_network_subnet.go
- data_types/softlayer_network_vlan.go
- data_types/softlayer_virtual_guest.go
- data_types/softlayer_virtual_guest_network_component.go
- services/softlayer_network_vlan.go
- services/softlayer_network_vlan_test.go
- services/softlayer_virtual_guest.go
- softlayer/client.go
- softlayer/softlayer_network_vlan_service.go
- test_fixtures/services/SoftLayer_Network_Vlan_Service_getObject.json
Added softlayer_network_vlan service
> Added softlayer_network_vlan service

- services/softlayer_network_storage.go
> set disk size to 1000 if < 1000

- client/http_client.go
- client/softlayer_client_test.go
Hi Dr.Max @maximilien,
This commit it to hide Softlayer credentials in error message. Please help to take a review. Thanks.
[#140904659](https://www.pivotaltracker.com/story/show/140904659)
> Hide Softlayer credentials in error message
